### ISSUE TITLE
Example code and "Push Access"

### ISSUE THREAD

**Issue by alexandrepecora** [Ramin-Hassan/RapidMiner-demonstration#4]
Hello group!

I found this code that might help us to understand how to do web scrapping.  It basically pull information about what ideas of crowdfunding were successful, to do so it scrapes info from this website: http://www.ideastorm.com/ (where implementation data is publicly available for each idea).

More information in: https://community.rapidminer.com/t5/RapidMiner-Studio-Forum/Web-Crawling-guide-help-much-needed/td-p/36410

I cannot upload a file code because I do not have "Push Access" according to Rapid Miner. Ramin, you as the project owner, do you know how to provide this "Push Access" access to us?

Thanks!

Here is the code:

<?xml version="1.0" encoding="UTF-8"?><process version="7.3.000">
  <context>
    <input/>
    <output/>
    <macros/>
  </context>
  <operator activated="true" class="process" compatibility="7.3.000" expanded="true" name="Process">
    <process expanded="true">
      <operator activated="true" class="web:get_webpage" compatibility="7.3.000" expanded="true" height="68" name="get page" width="90" x="45" y="34">
        <parameter key="url" value="http://www.ideastorm.com/idea2ExploreMore?v=1487149161389&amp;Type=TrendingIdeas"/>
        <parameter key="random_user_agent" value="true"/>
        <parameter key="connection_timeout" value="50000"/>
        <parameter key="read_timeout" value="50000"/>
        <parameter key="accept_cookies" value="all"/>
        <list key="query_parameters"/>
        <list key="request_properties"/>
      </operator>
      <operator activated="true" class="text:create_document" compatibility="7.3.000" expanded="true" height="68" name="Create Document" width="90" x="45" y="340">
        <parameter key="text" value="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&#10;&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;&#10;&lt;xsl:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot;/&gt;&#10;&lt;xsl:template match=&quot;/&quot;&gt;&#10;&lt;root&gt;&#10;&lt;xsl:for-each select=&quot;//article[@class='search-result']&quot;&gt;&#10;&lt;xsl:variable name=&quot;idea&quot; select=&quot;h3/a&quot;/&gt;&#10;&lt;xsl:variable name=&quot;added&quot; select=&quot;div[1]/p[@class='date']&quot;/&gt;&#10;&lt;xsl:variable name=&quot;votes&quot; select=&quot;div[1]/p[@class='votes']/em&quot;/&gt;&#10;&lt;xsl:variable name=&quot;details&quot; select=&quot;normalize-space(p[@class='truncatedBody'])&quot;/&gt;&#10;&lt;row idea=&quot;{$idea}&quot; added=&quot;{$added}&quot; votes=&quot;{$votes}&quot; details=&quot;{$details}&quot;/&gt;&#10;&lt;/xsl:for-each&gt;&#10;&lt;/root&gt;&#10;&lt;/xsl:template&gt;&#10;&lt;/xsl:stylesheet&gt;"/>
      </operator>
      <operator activated="true" class="text:html_to_xml" compatibility="7.3.000" expanded="true" height="68" name="HTML to XML" width="90" x="179" y="34"/>
      <operator activated="true" class="text:replace_tokens" compatibility="7.3.000" expanded="true" height="68" name="Replace Tokens" width="90" x="313" y="34">
        <list key="replace_dictionary">
          <parameter key="&lt;html[^&gt;]+&gt;" value="&lt;html&gt;"/>
          <parameter key="(?sm)&lt;!DOCTYPE[^&gt;]+&gt;(.)" value="$1"/>
        </list>
      </operator>
      <operator activated="true" class="text:combine_documents" compatibility="7.3.000" expanded="true" height="82" name="Combine Documents" width="90" x="45" y="238"/>
      <operator activated="true" class="text:process_xslt" compatibility="7.3.000" expanded="true" height="82" name="Process Xslt" width="90" x="179" y="238"/>
      <operator activated="true" class="text:cut_document" compatibility="7.3.000" expanded="true" height="68" name="Cut Document" width="90" x="179" y="646">
        <parameter key="query_type" value="Regular Region"/>
        <list key="string_machting_queries"/>
        <list key="regular_expression_queries"/>
        <list key="regular_region_queries">
          <parameter key="row" value="&lt;row./&gt;"/>
        </list>
        <list key="xpath_queries"/>
        <list key="namespaces"/>
        <list key="index_queries"/>
        <list key="jsonpath_queries"/>
        <process expanded="true">
          <operator activated="true" class="text:extract_information" compatibility="7.3.000" expanded="true" height="68" name="Extract Information" width="90" x="112" y="34">
            <parameter key="query_type" value="XPath"/>
            <list key="string_machting_queries"/>
            <list key="regular_expression_queries"/>
            <list key="regular_region_queries"/>
            <list key="xpath_queries">
              <parameter key="idea" value="//@idea"/>
              <parameter key="added" value="//@added"/>
              <parameter key="votes" value="//@votes"/>
              <parameter key="details" value="//@details"/>
            </list>
            <list key="namespaces"/>
            <list key="index_queries"/>
            <list key="jsonpath_queries"/>
          </operator>
          <connect from_port="segment" to_op="Extract Information" to_port="document"/>
          <connect from_op="Extract Information" from_port="document" to_port="document 1"/>
          <portSpacing port="source_segment" spacing="0"/>
          <portSpacing port="sink_document 1" spacing="0"/>
          <portSpacing port="sink_document 2" spacing="0"/>
        </process>
      </operator>
      <operator activated="true" class="text:documents_to_data" compatibility="7.3.000" expanded="true" height="82" name="Documents to Data" width="90" x="313" y="646">
        <parameter key="text_attribute" value="pages"/>
      </operator>
      <operator activated="true" class="select_attributes" compatibility="7.3.000" expanded="true" height="82" name="Select Attributes" width="90" x="447" y="646">
        <parameter key="attribute_filter_type" value="subset"/>
        <parameter key="attributes" value="pages|query_key"/>
        <parameter key="invert_selection" value="true"/>
        <parameter key="include_special_attributes" value="true"/>
      </operator>
      <connect from_op="get page" from_port="output" to_op="HTML to XML" to_port="document"/>
      <connect from_op="Create Document" from_port="output" to_op="Process Xslt" to_port="xslt document"/>
      <connect from_op="HTML to XML" from_port="document" to_op="Replace Tokens" to_port="document"/>
      <connect from_op="Replace Tokens" from_port="document" to_op="Combine Documents" to_port="documents 1"/>
      <connect from_op="Combine Documents" from_port="document" to_op="Process Xslt" to_port="document"/>
      <connect from_op="Process Xslt" from_port="document" to_op="Cut Document" to_port="document"/>
      <connect from_op="Cut Document" from_port="documents" to_op="Documents to Data" to_port="documents 1"/>
      <connect from_op="Documents to Data" from_port="example set" to_op="Select Attributes" to_port="example set input"/>
      <connect from_op="Select Attributes" from_port="example set output" to_port="result 1"/>
      <portSpacing port="source_input 1" spacing="0"/>
      <portSpacing port="sink_result 1" spacing="0"/>
      <portSpacing port="sink_result 2" spacing="0"/>
    </process>
  </operator>
</process>

**Comment by chen3912** [comment]
thx Alex!

**Comment by Ramin-Hassan** [comment]
Thanks Alex. We should look into the code. ALSO,  I did not know that. I'll look into it.
